### PR TITLE
Get the browser logos from their own packages

### PR DESCRIPTION
**Pull request by alrra**
Cc @digitarald

### CODE REVIEW

**Comment by digitarald** [comment]
Thank you @alrra for the patch and even more so, your work on the browser logo repo! Happy Holidays 🎄 🎅  🎁

**Comment by alrra** [comment]
@digitarald Happy Holidays to you, too!

**Comment by alrra** [comment]
@digitarald I did test locally if everything works as expected, and it did, but for some reason, the logos are missing on https://platform-status.mozilla.org/.

**Comment by marco-c** [comment]
Let's revert it for now.

**Pull request merged**
