### PR TITLE
adding significant features newly supported in Firefox 68

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Added BigInt and VisualViewport; updated some details of CSS Scroll Snap.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@digitarald / @marco-c could you please review this? I am a bit concerned because some previously added features don't seem to be showing on the site, like scroll snap and scroll anchoring.

**Comment by chrisdavidmills** [comment]
Also, the travis build fails with an arbitrary error message, and I'm not sure how to fix it.

**Comment by digitarald** [comment]
Potentially:

- CSS Scroll Snap
- WebAuthN on Fennec

**Comment by digitarald** [comment]
> Also, the travis build fails with an arbitrary error message, and I'm not sure how to fix it.

@chrisdavidmills I patched the travis config, lets try again.

**Comment by chrisdavidmills** [comment]
Thanks @digitarald. We already have an entry for Web Authn, but there isn't really a way to specify that it was supported in android in a different version. What would you suggest?

And do the other bits I've aded look OK?

The travis build is now passed.

**Comment by digitarald** [comment]
> We already have an entry for Web Authn, but there isn't really a way to specify that it was supported in android in a different version. What would you suggest?

We often previously set things to _supported_ even when only Android had it, like Manifest. That seems reasonable here as well, maybe with comment?

> And do the other bits I've aded look OK?

Yes.

**Comment by chrisdavidmills** [comment]
I think I'm going to merge this for now, and then I'll do some more thinking on how we can add such notes.

**Pull request merged**
